name: appwrite-nuxt-ssr-starter
services:
  nuxt:
    container_name: nuxt
    build:
      context: ./packages/nuxt
      target: "development"
    environment:
      NODE_ENV: development
      NUXT_PUBLIC_APPWRITE_ENDPOINT: ${APPWRITE_ENDPOINT}
      NUXT_PUBLIC_APPWRITE_PROJECT_ID: ${APPWRITE_PROJECT_ID}
      NODE_OPTIONS: "--use-openssl-ca"
      # For development, disable certificate verification
      # NODE_TLS_REJECT_UNAUTHORIZED: "0"
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./packages/nginx/ssl:/etc/ssl/certs
      - ./packages/nuxt:/usr/src/app/src

  nginx:
    build:
      context: ./packages/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nuxt
    volumes:
      - ./packages/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./packages/nginx/ssl:/etc/nginx/ssl

networks:
  default:
    driver: bridge
